### ISSUE TITLE
Possible regression with 0.11.x

### ISSUE THREAD

**Issue by geoffharcourt** [palkan/test-prof#174] opened 2020-02-11 01:04 UTC
### Tell us about your environment

**Ruby Version:**
2.6.5

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
Rails 6.0.2.1, rspec-rails 4.0.0.beta4, Rubocop 0.79.0

**TestProf Version:**
0.11.1

### What did you do?
`bundle exec rubocop`

### What did you expect to happen?
To have Rubocop run

### What actually happened?
We got this error:

```
❯ bex rubocop
undefined method `enlist' for nil:NilClass
/Users/geoff/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/test-prof-0.11.1/lib/test_prof/cops/rspec/aggregate_failures.rb:8:in `inherited'
/Users/geoff/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/test-prof-0.11.1/lib/test_prof/cops/rspec/aggregate_failures.rb:12:in `<module:RSpec>'
/Users/geoff/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/test-prof-0.11.1/lib/test_prof/cops/rspec/aggregate_failures.rb:5:in `<module:Cop>'
/Users/geoff/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/test-prof-0.11.1/lib/test_prof/cops/rspec/aggregate_failures.rb:4:in `<module:RuboCop>'
/Users/geoff/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/test-prof-0.11.1/lib/test_prof/cops/rspec/aggregate_failures.rb:3:in `<top (required)>'
/Users/geoff/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/test-prof-0.11.1/lib/test_prof/rubocop.rb:14:in `require'
/Users/geoff/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/test-prof-0.11.1/lib/test_prof/rubocop.rb:14:in `<top (required)>'
/Users/geoff/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.79.0/lib/rubocop/config_loader_resolver.rb:15:in `require'
```

**Comment by geoffharcourt** [comment] 2020-02-11 01:07
Notes: Rubocop runs if we downgrade to test-prof 0.10.2 (fails for 0.11.0 for the missing config issue patched today).

**Comment by palkan** [comment] 2020-02-11 01:07
@pirj Could you please take a look?

**Comment by pirj** [comment] 2020-02-11 10:17
🐞 👀

**Comment by palkan** [comment] 2020-02-11 17:09
@geoffharcourt Couldn't reproduce so far but changed the configuration a bit. Could you please check the `master` version?

**Comment by pirj** [comment] 2020-02-11 18:40
I was able to reproduce the issue with 0.11.1, but not on `master`, [this change](https://github.com/palkan/test-prof/commit/ce86d10577dc5528c840e040086872a76b2a00e7#diff-6bc3ee9ec86e5475223edf6b76fe650dR7) has fixed it.

**Comment by geoffharcourt** [comment] 2020-02-11 19:57
Running on `master` allowed me to run the cops (I got the warning for the renamed cop as expected).

**Comment by palkan** [comment] 2020-02-11 20:14
Thanks! Closing this and releasing a new patch version.

**Closed by palkan** 2020-02-11 20:14 UTC
Labels: bug, investigation required
